Add jobs aa1 to master
Aichner-Industries/homepage pull request #3
Opened 2020-08-06 14:35 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there is no job page.
- Currently there is no team page.

**What is the new behavior (if this is a feature change)?**
- A job page has been added.
- A team page has been added.

**Other information**:
- The version has been updated to `v1.1.0`.

2020-08-06 14:41 UTC, sweggerat approved these changes
good

2020-08-06 14:48 UTC, pinterid commented on src/components/pages/TeamPage/index.jsx
> +    snek: "https://snek.at/u/aichnerc",
```suggestion
    snek: "https://snek.at/u/Aichnerc",
```

2020-08-06 14:49 UTC, pinterid requested changes
Found one issue.

2020-08-06 15:07 UTC, Theralun requested changes
Have a look.

2020-08-06 15:07 UTC, Theralun commented on src/components/pages/PositionsPage/index.jsx
> +                    <li>Avionik</li>
Avionics

2020-08-06 15:50 UTC, Aichnerc commented on src/components/pages/PositionsPage/index.jsx
> +                    <li>Avionik</li>
Oh damn.

2020-08-06 16:49 UTC, Theralun approved these changes
LGTM.

2020-08-06 21:24 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-08-07 07:47 UTC, pinterid approved these changes

2020-08-07 08:22 UTC, merged